/**
 * Keywords cycled during the "Thinking..." animation.
 * Feel free to add, remove, or reorder entries.
 */
export const thinkingKeywords: string[] = [
    'Thinking...',
    'Pondering the cosmos...',
    'Consulting the void...',
    'Tickling tensors...',
    'Collapsing wavefunctions...',
    'Untangling gradients...',
    'Spinning up neurons...',
    'Warming the matrix...',
    'Herding photons...',
    'Calibrating synapses...',
    'Percolating insights...',
    'Shuffling embeddings...',
    'Summoning attention heads...',
    'Whispering to weights...',
    'Parsing the ether...',
    'Distilling knowledge...',
    'Braiding logic threads...',
    'Charging flux capacitor...',
    'Aligning dimensions...',
    'Folding latent space...',
    'Querying the oracle...',
    'Crunching tokens...',
    'Sifting through entropy...',
    'Mapping thought vectors...',
    'Brewing inference...',
    'Decoding possibilities...',
    'Wrangling parameters...',
    'Tuning hyperplanes...',
    'Spinning context windows...',
    'Traversing the graph...',
    'Invoking deep thought...',
    'Assembling coherence...',
    'Mining semantics...',
    'Tracing attention arcs...',
    'Crystallizing meaning...',
    'Weaving narratives...',
    'Stacking transformers...',
    'Compressing wisdom...',
    'Sampling the distribution...',
    'Negotiating with entropy...',
    'Refining the signal...',
    'Chasing eigenvectors...',
    'Probing feature space...',
    'Synthesizing reply...',
    'Bridging abstractions...',
    'Sculpting the response...',
    'Consulting the archives...',
    'Navigating embeddings...',
    'Gathering resonance...',
    'Harmonizing layers...',
    'Diffusing through noise...',
    'Propagating forward...',
    'Backpropagating vibes...',
    'Sketching hypotheses...',
    'Composing thoughts...',
    'Riffling through tokens...',
    'Channeling the model...',
    'Massaging probabilities...',
    'Indexing the unknown...',
    'Meditating on context...',
    'Parsing subtext...',
    'Unraveling complexity...',
    'Connecting dots...',
    'Forging understanding...',
    'Sieving signal from noise...',
    'Warming up layers...',
    'Interrogating the dataset...',
    'Cultivating responses...',
    'Resolving ambiguity...',
    'Mapping the manifold...',
    'Pruning decision trees...',
    'Generating candidates...',
    'Evaluating hypotheses...',
    'Cross-referencing memory...',
    'Refactoring thoughts...',
    'Decompressing knowledge...',
    'Surfing latent waves...',
    'Bootstrapping reasoning...',
    'Polishing the output...',
    'Iterating on ideas...',
    'Optimizing coherence...',
    'Balancing creativity...',
    'Fusing representations...',
    'Projecting meaning...',
    'Spinning inference wheels...',
    'Cascading through layers...',
    'Interleaving perspectives...',
    'Condensing the answer...',
    'Materializing insight...',
    'Resonating with context...',
    'Activating soft attention...',
    'Searching solution space...',
    'Expanding the beam...',
    'Collating evidence...',
    'Tempering the logits...',
    'Normalizing intuition...',
    'Orchestrating tokens...',
    'Extracting the essence...',
    'Simulating understanding...',
    'Calibrating confidence...',
    'Rendering cognition...',
    'Consulting inner layers...',
    'Mining for insight...',
    'Assembling the puzzle...',
    'Triangulating truth...',
    'Distilling the answer...',
    'Warming attention heads...',
    'Juggling perspectives...',
    'Sharpening predictions...',
    'Exploring the tree...',
    'Knitting concepts...',
    'Synthesizing clarity...',
    'Fermenting ideas...',
    'Crystallizing logic...',
    'Nurturing the response...',
    'Curating knowledge...',
    'Refining the draft...',
    'Polishing semantics...',
    'Scanning the horizon...',
    'Decrypting patterns...',
    'Weaving the tapestry...',
    'Channeling coherence...',
    'Coalescing fragments...',
    'Spiraling through thought...',
    'Transmuting data...',
    'Conjuring relevance...',
    'Distilling experience...',
    'Incubating the answer...',
    'Percolating through layers...',
    'Radiating computation...',
    'Converging on truth...',
    'Illuminating pathways...',
    'Unfurling the response...',
    'Catalyzing insight...',
    'Harmonizing signals...',
    'Precipitating meaning...',
    'Reverberating through context...',
    'Transmitting thought...',
    'Kindling understanding...',
    'Orchestrating neurons...',
    'Igniting inference...',
    'Sublimating tokens...',
    'Condensing the cosmos...',
    'Dissolving uncertainty...',
    'Manifesting the reply...',
    'Alchemizing input...',
    'Crystallizing the draft...',
    'Breathing life into bytes...',
    'Tuning the resonance...',
    'Composing the symphony...',
    'Decanting wisdom...',
    'Forging the response...',
    'Tempering insight...',
    'Etching understanding...',
    'Almost there...',
];
